version: "3.5"
services:
  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
  api:
    build: ./api/.
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api/.:/myapp
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: ${REDIS_URL}
      PGHOST: ${PGHOST}
      PGUSER: ${PGUSER}
      PGPASSWORD: ${PGPASSWORD}
    depends_on:
      - db
  frontend:
    build: ./frontend/
    volumes:
      - ./frontend/.:/app
    ports:
      - "3005:3000"
    command: npm start
